services:
  - type: web
    name: pokemongo-announce-watcher
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 pokemongo_announce_watcher.py
    healthCheckPath: /health
